# Generated by Django 6.0.4 on 2026-04-09 02:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tecnicos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cotizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(editable=False, max_length=20, unique=True)),
                ('nombre_cliente', models.CharField(max_length=200)),
                ('telefono', models.CharField(max_length=20)),
                ('correo', models.EmailField(max_length=254)),
                ('direccion', models.TextField()),
                ('distrito', models.CharField(max_length=100)),
                ('referencias', models.TextField(blank=True)),
                ('tipo_uso', models.CharField(choices=[('residencial', 'Residencial'), ('comercial', 'Comercial'), ('industrial', 'Industrial')], max_length=20)),
                ('descripcion', models.TextField()),
                ('disponibilidad', models.CharField(max_length=200)),
                ('estado', models.CharField(choices=[('recibido', 'Recibido'), ('en_revision', 'En Revision'), ('visita_agendada', 'Visita Agendada'), ('cotizado', 'Cotizado'), ('aceptado', 'Aceptado'), ('rechazado', 'Rechazado'), ('instalacion_agendada', 'Instalacion Agendada'), ('en_instalacion', 'En Instalacion'), ('completado', 'Completado'), ('cancelado', 'Cancelado')], default='recibido', max_length=30)),
                ('motivo_rechazo', models.TextField(blank=True)),
                ('token_unico', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cotizacion',
                'verbose_name_plural': 'Cotizaciones',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='CotizacionFormal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion_producto', models.TextField()),
                ('lista_materiales', models.TextField()),
                ('costo_materiales', models.DecimalField(decimal_places=2, max_digits=10)),
                ('costo_mano_obra', models.DecimalField(decimal_places=2, max_digits=10)),
                ('costo_instalacion', models.DecimalField(decimal_places=2, max_digits=10)),
                ('costo_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tiempo_instalacion', models.CharField(max_length=100)),
                ('condiciones_pago', models.TextField()),
                ('meses_garantia', models.IntegerField(default=12)),
                ('validez_dias', models.IntegerField(default=15)),
                ('terminos', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('cotizacion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cotizacion_formal', to='cotizaciones.cotizacion')),
            ],
            options={
                'verbose_name': 'Cotizacion Formal',
                'verbose_name_plural': 'Cotizaciones Formales',
            },
        ),
        migrations.CreateModel(
            name='ImagenCotizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='cotizaciones/')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('cotizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='cotizaciones.cotizacion')),
            ],
        ),
        migrations.CreateModel(
            name='VisitaTecnica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('estado', models.CharField(choices=[('programada', 'Programada'), ('completada', 'Completada'), ('cancelada', 'Cancelada'), ('reprogramada', 'Reprogramada')], default='programada', max_length=20)),
                ('medidas', models.TextField(blank=True)),
                ('observaciones', models.TextField(blank=True)),
                ('dificultad', models.CharField(blank=True, max_length=20)),
                ('tiempo_estimado', models.CharField(blank=True, max_length=100)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('cotizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitas', to='cotizaciones.cotizacion')),
                ('tecnico', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visitas_cotizacion', to='tecnicos.tecnico')),
            ],
            options={
                'verbose_name': 'Visita Tecnica',
                'verbose_name_plural': 'Visitas Tecnicas',
            },
        ),
        migrations.CreateModel(
            name='ImagenVisita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='visitas/')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('visita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='cotizaciones.visitatecnica')),
            ],
        ),
    ]
