# Generated by Django 6.0.4 on 2026-05-24 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0002_mensajecontacto'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacionformal',
            name='pdf_cotizacion',
            field=models.FileField(blank=True, null=True, upload_to='cotizaciones_pdf/'),
        ),
    ]
