# Generated by Django 6.0.4 on 2026-05-24 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0003_cotizacionformal_pdf_cotizacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacionformal',
            name='materiales_necesarios',
            field=models.TextField(blank=True),
        ),
    ]
