# Generated by Django 6.0.4 on 2026-05-24 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0004_cotizacionformal_materiales_necesarios'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cotizacionformal',
            name='materiales_necesarios',
        ),
        migrations.AddField(
            model_name='visitatecnica',
            name='materiales_necesarios',
            field=models.TextField(blank=True),
        ),
    ]
