# Generated by Django 6.0.4 on 2026-04-09 02:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tecnicos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(editable=False, max_length=20, unique=True)),
                ('nombre_cliente', models.CharField(max_length=200)),
                ('telefono', models.CharField(max_length=20)),
                ('correo', models.EmailField(max_length=254)),
                ('direccion', models.TextField()),
                ('distrito', models.CharField(max_length=100)),
                ('tipo_puerta', models.CharField(max_length=100)),
                ('fecha_instalacion_aprox', models.DateField(blank=True, null=True)),
                ('descripcion_problema', models.TextField()),
                ('disponibilidad', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('preventivo', 'Mantenimiento Preventivo'), ('correctivo', 'Mantenimiento Correctivo'), ('garantia', 'Garantia')], max_length=20)),
                ('estado', models.CharField(choices=[('recibido', 'Recibido'), ('en_revision', 'En Revision'), ('diagnostico_remoto', 'Diagnostico Remoto'), ('visita_agendada', 'Visita Agendada'), ('en_proceso', 'En Proceso'), ('esperando_repuestos', 'Esperando Repuestos'), ('resuelto', 'Resuelto'), ('cancelado', 'Cancelado')], default='recibido', max_length=30)),
                ('garantia_vigente', models.BooleanField(default=False)),
                ('token_unico', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('fecha_proximo_mantenimiento', models.DateField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Mantenimiento',
                'verbose_name_plural': 'Mantenimientos',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='ImagenMantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='mantenimientos/')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('mantenimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='mantenimientos.mantenimiento')),
            ],
        ),
        migrations.CreateModel(
            name='Testimonio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cliente', models.CharField(max_length=200)),
                ('calificacion', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('comentario', models.TextField()),
                ('aprobado', models.BooleanField(default=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('mantenimiento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='testimonios', to='mantenimientos.mantenimiento')),
            ],
            options={
                'verbose_name': 'Testimonio',
                'verbose_name_plural': 'Testimonios',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='VisitaMantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('estado', models.CharField(choices=[('programada', 'Programada'), ('completada', 'Completada'), ('cancelada', 'Cancelada'), ('reprogramada', 'Reprogramada')], default='programada', max_length=20)),
                ('diagnostico', models.TextField(blank=True)),
                ('trabajos_realizados', models.TextField(blank=True)),
                ('repuestos_utilizados', models.TextField(blank=True)),
                ('costo_total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('mantenimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitas', to='mantenimientos.mantenimiento')),
                ('tecnico', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visitas_mantenimiento', to='tecnicos.tecnico')),
            ],
            options={
                'verbose_name': 'Visita de Mantenimiento',
                'verbose_name_plural': 'Visitas de Mantenimiento',
            },
        ),
        migrations.CreateModel(
            name='ImagenVisitaMantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='visitas_mantenimiento/')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('visita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='mantenimientos.visitamantenimiento')),
            ],
        ),
    ]
