# Generated by Django 6.0.4 on 2026-05-26 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimientos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitamantenimiento',
            name='foto_mantenimiento',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_mantenimiento/'),
        ),
    ]
